Add drive api
arowM/haskell-google-server-api pull request #2
Opened 2020-05-19 11:34 UTC by qnoyxu

This PR adds some functions to manipulate files on Google Drive.

Please see [here](https://github.com/qnoyxu/tonatona-google-server-api/tree/add-drive-api/sample) for a sample code.

2020-05-19 16:26 UTC, arowM commented
Cool!
It seems CI fails, so could you check and fix it?

2020-05-20 05:22 UTC, qnoyxu commented
I've fixed package dependencies.

2020-05-20 05:59 UTC, arowM requested changes

2020-05-20 05:59 UTC, arowM commented on src/Google/Client.hs
> +exportDriveFile token fileId mimeType = do
I would like to make `mimeType` and `fileId` type safe.
Is it possible to create new type `MimeType` and `FileId`?

The `query` and `orderBy` used elsewhere should also be type safe, but if it's too labor intensive, you can just leave it.

2020-05-21 09:52 UTC, qnoyxu commented
Commit [cdc5f8b](https://github.com/qnoyxu/haskell-google-server-api/commit/cdc5f8b80137c08f40b2a2825e9d826b39a73c38) makes some types safe.
I created new type of `query` by simply wrapping `Text` because it seems to be used only here and its syntax is complicated.

Commit [914af55](https://github.com/qnoyxu/haskell-google-server-api/commit/914af55fd6aa86ff7f66984ed9dc2985c589e174) renames 'exportDriveFile' to 'downloadDriveFile'.

2020-05-21 10:34 UTC, arowM commented
I apologize for not being explicit, and for going through your previous PR, but the `Form` module is actually supposed to export a chunk of data that you want to create such as `Form.CalendarEvent`.

2020-05-21 11:45 UTC, qnoyxu commented
I'm not sure I understand what 'chunk' means, but does it mean that not only the type that represents `contentType`, but also types that have a single field (such as `FileId`), should be exported from another file?

2020-05-21 15:08 UTC, arowM commented
Yeah, it's what I meant.
There are two ways to design `downloadDriveFIle` API:
a. Take token and two arguments fileId and mimeType exported from some modules such as `Type` you made before
b. Take token and one argument exported from `Form`
    ```
    { fileId :: Text
    , mimeType :: MimeType
    }
    ```

2020-05-22 08:12 UTC, qnoyxu commented
Thanks for the great suggestions!
I changed type definitions accoding to the proposal b.
The types which were exported from `Form` and `Response` respectively such as `FileId` are now commonized.

2020-05-22 08:45 UTC, arowM commented
Great!

Could you create a new PR adding your sample directory?
It's helpfull.

2020-05-22 08:45 UTC, merged